---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tacnwddf/fuerzatacna.tacnavuelveasonreir.com/
    - /bin/rsync -av --delete --exclude='.git*' --exclude='.cpanel.yml' --exclude='actualizar.php' ./ "$DEPLOYPATH"