name: Despliegue Automatico Ninja
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Llamar al túnel secreto (Plan Z)"
        run: |
          curl -s -X POST -d "cpanel_user=${{ secrets.CPANEL_USER }}" -d "cpanel_token=${{ secrets.CPANEL_TOKEN }}" "https://fuerzatacna.tacnavuelveasonreir.com/actualizar.php"
